//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Chapter4_InteractiveDataPaging;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Sales _Sales = new Sales();

		public Sales Sales
		{
			get
			{
				return this._Sales;
			}
		}
	}

	public class SalesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _CompanyName = string.Empty;

		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}

			set
			{
				if (this._CompanyName != value)
				{
					this._CompanyName = value;
					this.OnPropertyChanged("CompanyName");
				}
			}
		}

		private string _SalesPerson = string.Empty;

		public string SalesPerson
		{
			get
			{
				return this._SalesPerson;
			}

			set
			{
				if (this._SalesPerson != value)
				{
					this._SalesPerson = value;
					this.OnPropertyChanged("SalesPerson");
				}
			}
		}

		private double _SalesAmount = 0;

		public double SalesAmount
		{
			get
			{
				return this._SalesAmount;
			}

			set
			{
				if (this._SalesAmount != value)
				{
					this._SalesAmount = value;
					this.OnPropertyChanged("SalesAmount");
				}
			}
		}

		private double _SalesForecast = 0;

		public double SalesForecast
		{
			get
			{
				return this._SalesForecast;
			}

			set
			{
				if (this._SalesForecast != value)
				{
					this._SalesForecast = value;
					this.OnPropertyChanged("SalesForecast");
				}
			}
		}
	}

	public class Sales : System.Collections.ObjectModel.ObservableCollection<SalesItem>
	{ 
	}
#endif
}
