//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Chapter4_LazyLoadingListBoxData;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Companies _Companies = new Companies();

		public Companies Companies
		{
			get
			{
				return this._Companies;
			}
		}
	}

	public class CompaniesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _AccountAcquired = string.Empty;

		public string AccountAcquired
		{
			get
			{
				return this._AccountAcquired;
			}

			set
			{
				if (this._AccountAcquired != value)
				{
					this._AccountAcquired = value;
					this.OnPropertyChanged("AccountAcquired");
				}
			}
		}

		private string _CompanyName = string.Empty;

		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}

			set
			{
				if (this._CompanyName != value)
				{
					this._CompanyName = value;
					this.OnPropertyChanged("CompanyName");
				}
			}
		}
	}

	public class Companies : System.Collections.ObjectModel.ObservableCollection<CompaniesItem>
	{ 
	}
#endif
}
