//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleDataSource { }
#else

	public class SampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/LocalCommunicationConsumer;component/SampleData/SampleDataSource/SampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _Age = 0;

		public double Age
		{
			get
			{
				return this._Age;
			}

			set
			{
				if (this._Age != value)
				{
					this._Age = value;
					this.OnPropertyChanged("Age");
				}
			}
		}

		private bool _Male = false;

		public bool Male
		{
			get
			{
				return this._Male;
			}

			set
			{
				if (this._Male != value)
				{
					this._Male = value;
					this.OnPropertyChanged("Male");
				}
			}
		}

		private string _Names = string.Empty;

		public string Names
		{
			get
			{
				return this._Names;
			}

			set
			{
				if (this._Names != value)
				{
					this._Names = value;
					this.OnPropertyChanged("Names");
				}
			}
		}

		private bool _Retired = false;

		public bool Retired
		{
			get
			{
				return this._Retired;
			}

			set
			{
				if (this._Retired != value)
				{
					this._Retired = value;
					this.OnPropertyChanged("Retired");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
